apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: andrewazchcaptureorder 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: andrewazchcaptureorder 
    spec:
      containers:
        - name: andrewazchcaptureorder 
          image: registrodockerazure.azurecr.io/andrewazchcaptureorder
          ports:
          - containerPort: 8080